### ISSUE TITLE
MemberService 추가 코드 리뷰 질문

### ISSUE THREAD

**Issue by Moveuk** [architrave-dev/backend#13]
코드 리뷰 당시에 읽으면서 말씀을 드렸어야 했는데 죄송합니다~

다름이 아니라 아래 코드에서 Optional을 사용함에 있어 다소 부자연스러움이 있어 이슈 발행합니다.

```java
    @Transactional(readOnly = true)
    public Member findMemberById(Long memberId) {
        return memberRepository.findById(memberId)
                .orElse(null);
    }
    @Transactional(readOnly = true)
    public Member findMemberById(Member member) {
        return memberRepository.findById(member.getId())
                .orElse(null);
    }

    @Transactional(readOnly = true)
    public Member findMemberByAui(String aui) {
        return memberRepository.findByAui(aui)
                .orElse(null);
    }
```

위 코드에서 Optional을 받아서 orElse처리를 해주셨는데 그것을 다시 null로 보내게 되면 반환시 null이 나간다는 것인데 의도한 것일까요?

제가 생각하기에는 orElse로 어떤 특정한 값을 넘겨주고 싶은 것이 아니라면 orThrow로 회원이 조회되지 않았기 때문에 예외를 터트리는게 맞는 것같습니다.

그런데 사용처를 보니 Test에서 사용하고 있는 것 같더라구요.

removeTest에서 삭제 되었는지를 확인 하고 싶은 것이라면 예외가 터졌는지를 확인하는 것이 나은 방법일 것 같습니다.

```
        //then
        Assertions.assertNull(memberService.findMemberById(afterCreateMember));
```

뭔가 테스트코드에서 null임을 증명하기 위해서 어플리케이션 코드를 테스트코드를 위한 코드로 작성한 것 같아요!

정리해보자면 제 생각에

1. Optional의 orElse는 null일 때 NPE를 피하기 위해 다른 값을 내보내도록하는 메소드인데 메소드의 사용 의도와는 반대로 null을 내보내는 것 같아 이상해보입니다.
2. Repository에서 데이터를 조회해오지 못한다면 null을 내보내는 것이 아니라 Exception으로 바로 처리해주는 것이 자연스러워 보입니다.
3. 이를 수정하기 위해 테스트 코드에서 null임을 확인하지 말고 Exception을 확인하면 될 것 같습니다.

---

한번 생각해보시고 의도한 바가 있으시다면 그냥 코드를 두시고 이 이슈를 닫으시면 될 것 같습니다!

혹은 코드를 변경하게 되어 이 의논이 닫히게 되면 추후에 PR에서 이 issue를 닫으면 될 듯 합니다.

---

p.s. 제가 요즘 공부 매너리즘이 와서 좀 게을러진거 같네요. ㅜㅜ 죄송해요~ 날 더운데 화이팅하시죠~~

**Comment by youngdong82** [comment]
null로 리턴 한 다음 
한단계 바깥에서 null일 경우 Exception을 보내려고 의도한것이긴 한데
말씀하신대로 변경하는 것이 더 깔끔할 것 같네요!!

일단 이슈를 유지하고 변경한 후 닫겠습니다!!

**Comment by youngdong82** [comment]
아이고ㅠ 매너리즘이 오셨군요ㅠㅠ 괜찮아지시면 언제든지 돌아오세요!!!ㅋㅋㅋㅋ 
아니면 얘기를 나눠볼까요??

**Comment by Moveuk** [comment]
말씀이라도 감사하네요! :) 지금은 좀 나아져서 다시 공부를 해보려고 합니다!
커리어는 안쌓이고 그냥 토이프로젝트만 계속 쌓는것 같아서ㅋㅋ 좀 스트레스가 쌓이나봐요ㅋㅋ

알겠습니다 열어놓고 추후에 처리되면 닫으시죠~

**Comment by youngdong82** [comment]
제가 상황을 완벽하게 이해할 수는 없겠지만ㅠ 글만 봐도 힘드실 것 같네요ㅠㅠ

저는 동욱님이랑 해서 다행이라 생각하고 엄청 도움을 받고 있는데 말이죠ㅠ

그래도 동욱님은 확실하게 실력이 있으시니까 힘내셨으면 좋겠습니다!!

**Comment by youngdong82** [comment]
null을 리턴하는 것을 Exception을 리턴하는 것으로 변경했습니다.
