### ISSUE TITLE
프론트 팀 제공을 위한 Swagger 세팅

### ISSUE THREAD

**Issue by Moveuk** [architrave-dev/backend#5]

**Comment by youngdong82** [comment]
- [ ] swagger webmvc ui 적용

- [ ] API 사용자를 위해 각 메소드에 주석 추가

- [ ] Work를 제외한 모든 ServiceTest, Postman2를 활용한 모든 ControllerTest 확인

- [ ] ServiceTest에서 데이터 격리성을 위해 @DirtiesContext 추가, EntityManger 제거
